name: Generate Deriv App ID

on:
  push:
    branches:
      - main

jobs:
  generate_app_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate App ID
        uses: binary-com/deriv-app-id-generator-action@v1
        with:
          DERIV_API_TOKEN: ${{ secrets.DERIV_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
