name: Generate Deriv App ID

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-app-id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to the latest version
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jq

      - name: Generate Deriv App ID
        run: |
          curl -X POST "https://api.deriv.com/app/register" \
          -H "Authorization: Bearer ${{ secrets.DERIV_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"name": "My App", "scopes": ["read", "trade"], "github_url": "https://github.com/punch-ish/mybot"}' \
          -o response.json
          echo "Full Response:"
          cat response.json  # Print the full response for debugging
          APP_ID=$(cat response.json | jq -r '.app_id')
          echo "Generated App ID: $APP_ID"
        env:
          DERIV_API_TOKEN: ${{ secrets.DERIV_API_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Output Response for Debugging
        run: cat response.json
